### PR TITLE
Use SKIP LOCKED to speed up lookups where using large numbers of workers

### PR DESCRIPTION
**Pull request by JasonHerr**
Thanks to research by @MSch done here:
https://github.com/QueueClassic/queue_classic/issues/279

- [x] Test in a heavy performance scenario
- [ ] Create PR into QueueClassic/queue_classic

### CODE REVIEW

**Review by cmdrclueless — APPROVED** [review]

**Comment by JasonHerr** [comment]
@cmdrclueless @jsylvia when I restart QC in the middle of a big query it cleans up dead locks.  However this causes a massive contention if the list of QC jobs is huge:

https://github.com/sunbirddcim/queue_classic/blob/master/lib/queue_classic.rb#L104

Should I add skip locked to this update?

**Comment by cmdrclueless** [comment]
Have you tried it to see how it performs?

**Comment by JasonHerr** [comment]
It's VERY hard to get it in a bad state like that...

**Comment by JasonHerr** [comment]
Got it into the state with a load of items in the queue and did not see queues blocking on that query any more when I restarted queue classic in the middle of the process. I am going to leave that issue for another day.

When approving, please do not delete this branch.

**Review by cschulze — APPROVED** [review]

**Review by straggler7 — APPROVED** [review]

**Pull request merged**
